name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute Tests
        run: vendor/bin/phpunit --testdox --colors=always
      # - name: Install front-end dependencies
      #   run: rm -r public/css && rm -r public/js && npm install && npm run prod
